USE `pear`;

DROP PROCEDURE IF EXISTS `PProductAdd`;
DROP PROCEDURE IF EXISTS `PProductGetAll`;
DROP PROCEDURE IF EXISTS `PProductGetAviable`;
DROP PROCEDURE IF EXISTS `PProductUpdate`;
DROP PROCEDURE IF EXISTS `PProductArchive`;
DROP PROCEDURE IF EXISTS `POrderAdd`;
DROP PROCEDURE IF EXISTS `POrdersGetByCustomer`;
DROP PROCEDURE IF EXISTS `PEmployeeAdd`;
DROP PROCEDURE IF EXISTS `PCustomerRegister`;
DROP PROCEDURE IF EXISTS `PCustomerDelete`;
DROP PROCEDURE IF EXISTS `PQuestionAsk`;
DROP PROCEDURE IF EXISTS `PQuestionAnswer`;

DROP TABLE IF EXISTS `Answer`;
DROP TABLE IF EXISTS `Question`;
DROP TABLE IF EXISTS `OrderDetail`;
DROP TABLE IF EXISTS `Order`;
DROP TABLE IF EXISTS `Employee`;
DROP TABLE IF EXISTS `Customer`;
DROP TABLE IF EXISTS `Product`;
DROP TABLE IF EXISTS `SalesPoint`;
DROP TABLE IF EXISTS `Administrator`;
DROP TABLE IF EXISTS `City`;
DROP TABLE IF EXISTS `Country`;
DROP TABLE IF EXISTS `SalesTerritory`;
